### ISSUE TITLE
error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by payyavularajasekharholcim** [code-farmz/ng-otp-input#104]
<img width="574" alt="image" src="https://github.com/code-farmz/ng-otp-input/assets/120568509/37a99b99-eaf0-464d-98fd-730cb98eede8">

**Comment by code-farmz** [comment]
use version 1.9.2 i just published

**Comment by payyavularajasekharholcim** [comment]
Thanks for the resolution @code-farmz
