### ISSUE TITLE
Angular Universal - ReferenceError: document is not defined

### ISSUE THREAD

**Issue by sameeradamith** [code-farmz/ng-otp-input#105]
Hello,

I attempted to utilise this wonderful package on Angular Universal/SSR, however it returned "ERROR ReferenceError: document is not defined."
I believe it is raised on line 201 of the  **"ng-otp-input/projects/ng-otp-input/src/lib/components/ng-otp-input/ng-otp-input.component.ts"** file. 
```
`    
   if (!this.config.disableAutoFocus) {
      const containerItem = document.getElementById('c_${this.componentKey}');
      var indexOfElementToFocus = value.length < this.config.length ? value.length : (this.config.length - 1);
      let ele : any = containerItem.getElementsByClassName('otp-input')[indexOfElementToFocus];
      if (ele && ele.focus) {
        ele.focus();
      }
     }
     this.rebuildValue();
  }`
```

So I'm hoping you can come up with a solution. Thank you very much.

Angular version: 15.2.9
ng-otp-input: 1.9.2

**Comment by code-farmz** [comment]
@sameeradamith  can you check with latest version i.e 1.9.3

**Comment by code-farmz** [comment]
closing as no response
