### ISSUE TITLE
Issue with keyboard "Enter" when the curser is inside the OTP fields

### ISSUE THREAD

**Issue by ahmad-paliotec** [code-farmz/ng-otp-input#106]
I have form that contain "Previous" and "Next" buttons for signup proccess. My issue that when the user finish input all the otp digits and press enter from the keyboard, then page go to previous screen like if the user click on button "Previous". How we can change the behavior to force use "Next" button instead ?

**Comment by code-farmz** [comment]
this is not  `ng-otp-input` component-related question please refer to other community sites like SO to get help on this.
