### ISSUE TITLE
Keypad clipboard not support in Mobile

### ISSUE THREAD

**Issue by kashinath0202** [code-farmz/ng-otp-input#108]
When get OTP in mobile that opt is copy then Keypad clipboard click after do not pest all input fields only one first inpu

https://github.com/code-farmz/ng-otp-input/assets/113377099/aed5e371-68a4-426f-8a13-146c371f5b89

t field pest - How to fix this please help me

**Comment by code-farmz** [comment]
should be working fine in latest version
