### ISSUE TITLE
Mac Safari issue.

### ISSUE THREAD

**Issue by ksabariraj** [code-farmz/ng-otp-input#11]
Good Day,

Could you please help on the below issue.

In safari, text box automatically insert enter and the value went down as mention in the below screenshot.

FYI,
in `onInputChange` i'm get value as 

"111
1
1"

<img width="369" alt="Screenshot 2019-09-28 at 10 09 13 PM" src="https://user-images.githubusercontent.com/3765085/65819643-9a878a80-e23c-11e9-9b0d-75377c56c847.png">

Just do backspace and enter value multiple times 

Thanks,
Sabari.

**Comment by code-farmz** [comment]
Hi thanks for pointing it out will check it out or meanwhile if you can try to fix it out and create a pull request that would be great

**Comment by code-farmz** [comment]
@ksabariraj  this is fixed now in latest version
