### ISSUE TITLE
The component cannot be styled properly via class

### ISSUE THREAD

**Issue by madalinabo** [code-farmz/ng-otp-input#112]
If the input class name is passed in the config object, the desired style cannot be passed to that class from the parent component because of the style encapsulation. 
To fix this undesired behaviour I would suggest either to change the encapsulation mode of the component, or to enable the outside styling with css variables.

**Comment by code-farmz** [comment]
You can use inputStyles property in the config object for eg  `{borderColor:'red'}` will set border color to red for all inputs
