### ISSUE TITLE
No provider for keyspipe 

### ISSUE THREAD

**Issue by logicappsource** [code-farmz/ng-otp-input#116]
addPhoneAndVerifyWithSms.ts:100 ERROR NullInjectorError: NullInjectorError: No provider for KeysPipe!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at ChainedInjector.get (core.mjs:15723:36)
    at lookupTokenUsingModuleInjector (core.mjs:5730:39)
    at getOrCreateInjectable (core.mjs:5778:12)
    at Module.ɵɵdirectiveInject (core.mjs:11050:19)
    at NodeInjectorFactory.NgOtpInputComponent_Factory [as factory] (ng-otp-input.mjs:38:114)
    at getNodeInjectable (core.mjs:5984:44)
    at instantiateAllDirectives (core.mjs:11907:27)
handleError @ core.mjs:6531
(anonymous) @ core.mjs:31943
invoke @ zone.js:365
run @ zone.js:111
runOutsideAngular @ core.mjs:14778
(anonymous) @ core.mjs:31943
_tick @ core.mjs:31530
tick @ core.mjs:31510
(anonymous) @ core.mjs:31891
invoke @ zone.js:365
onInvoke @ core.mjs:14882
invoke @ zone.js:364
run @ zone.js:111
run @ core.mjs:14733
next @ core.mjs:31890
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:6845
checkStable @ core.mjs:14801
onLeave @ core.mjs:14932
onInvokeTask @ core.mjs:14876
invokeTask @ zone.js:397
runTask @ zone.js:158
invokeTask @ zone.js:479
invokeTask @ zone.js:1105
globalCallback @ zone.js:1148
globalZoneAwareCallback @ zone.js:1169
load (async)
customScheduleGlobal @ zone.js:1253
scheduleTask @ zone.js:384
onScheduleTask @ core.mjs:14551
scheduleTask @ zone.js:378
onScheduleTask @ zone.js:267
scheduleTask @ zone.js:378
scheduleTask @ zone.js:201
scheduleEventTask @ zone.js:227
(anonymous) @ zone.js:1421
(anonymous) @ http.mjs:2282
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
source.subscribe.isComplete @ switchMap.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ switchMap.js:10
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ tap.js:15
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ finalize.js:5
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ finalize.js:5
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
doInnerSub @ mergeInternals.js:19
outerNext @ mergeInternals.js:14
OperatorSubscriber._next @ OperatorSubscriber.js:13
next @ Subscriber.js:31
(anonymous) @ innerFrom.js:51
_trySubscribe @ Observable.js:37
(anonymous) @ Observable.js:31
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
mergeInternals @ mergeInternals.js:50
(anonymous) @ mergeMap.js:13
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ filter.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
(anonymous) @ map.js:6
(anonymous) @ lift.js:10
(anonymous) @ Observable.js:26
errorContext @ errorContext.js:19
subscribe @ Observable.js:22
buttonClicked @ addPhoneAndVerifyWithSms.ts:100
addPhoneAndVerifyWithSms_div_6_Template_button_click_13_listener @ addPhoneAndVerifyWithSms.html:120
executeListenerWithErrorHandling @ core.mjs:25630
wrapListenerIn_markDirtyAndPreventDefault @ core.mjs:25664
(anonymous) @ platform-browser.mjs:679
invokeTask @ zone.js:398
(anonymous) @ core.mjs:14556
onInvokeTask @ core.mjs:14556
invokeTask @ zone.js:397
onInvokeTask @ core.mjs:14869
invokeTask @ zone.js:397
runTask @ zone.js:158
invokeTask @ zone.js:479
invokeTask @ zone.js:1105
globalCallback @ zone.js:1136
globalZoneAwareCallback @ zone.js:1169
Zone - HTMLButtonElement.addEventListener:click (async)
onScheduleTask @ core.mjs:14550
scheduleTask @ zone.js:378
onScheduleTask @ zone.js:267
scheduleTask @ zone.js:378
scheduleTask @ zone.js:201
scheduleEventTask @ zone.js:227
(anonymous) @ zone.js:1421
addEventListener @ platform-browser.mjs:779
addEventListener @ platform-browser.mjs:202
listen @ platform-browser.mjs:659
listen @ browser.mjs:4639
listenerInternal @ core.mjs:25591
ɵɵlistener @ core.mjs:25472
addPhoneAndVerifyWithSms_div_6_Template @ addPhoneAndVerifyWithSms.html:120
executeTemplate @ core.mjs:11268
renderView @ core.mjs:12470
createAndRenderEmbeddedLView @ core.mjs:12540
createEmbeddedViewImpl @ core.mjs:13393
createEmbeddedView @ core.mjs:16191
_updateView @ common.mjs:3408
set ngIf @ common.mjs:3382
applyValueToInputField @ core.mjs:4035
writeToDirectiveInput @ core.mjs:11096
setInputsForProperty @ core.mjs:12391
elementPropertyInternal @ core.mjs:11692
ɵɵproperty @ core.mjs:21281
addPhoneAndVerifyWithSms_Template @ addPhoneAndVerifyWithSms.html:33
executeTemplate @ core.mjs:11268
refreshView @ core.mjs:12791
detectChangesInView$1 @ core.mjs:13015
detectChangesInViewIfAttached @ core.mjs:12978
detectChangesInComponent @ core.mjs:12967
detectChangesInChildComponents @ core.mjs:13028
refreshView @ core.mjs:12841
detectChangesInView$1 @ core.mjs:13015
detectChangesInViewIfAttached @ core.mjs:12978
detectChangesInEmbeddedViews @ core.mjs:12935
refreshView @ core.mjs:12815
detectChangesInView$1 @ core.mjs:13015
detectChangesInViewIfAttached @ core.mjs:12978
detectChangesInComponent @ core.mjs:12967
detectChangesInChildComponents @ core.mjs:13028
refreshView @ core.mjs:12841
detectChangesInView$1 @ core.mjs:13015
detectChangesInViewWhileDirty @ core.mjs:12732
detectChangesInternal @ core.mjs:12714
detectChangesInView @ core.mjs:31723
detectChangesInViewIfRequired @ core.mjs:31696
detectChangesInAttachedViews @ core.mjs:31551
_tick @ core.mjs:31521
tick @ core.mjs:31510
(anonymous) @ core.mjs:31891
invoke @ zone.js:365
onInvoke @ core.mjs:14882
invoke @ zone.js:364
run @ zone.js:111
run @ core.mjs:14733
next @ core.mjs:31890
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:34
errorContext @ errorContext.js:19
next @ Subject.js:27
emit @ core.mjs:6845
checkStable @ core.mjs:14801
onLeave @ core.mjs:14932
onInvokeTask @ core.mjs:14876
invokeTask @ zone.js:397
runTask @ zone.js:158
invokeTask @ zone.js:479
invokeTask @ zone.js:1105
globalCallback @ zone.js:1136
globalZoneAwareCallback @ zone.js:1169
Show 184 more frames
Show less

**Comment by code-farmz** [comment]
key pipe removed in latest version and replaced by static utility
