### ISSUE TITLE
How can I check the validity for OTP 

### ISSUE THREAD

**Issue by kcss-ashvini** [code-farmz/ng-otp-input#117]
I'm using formControl for getting the value of OTP. I wanted to apply the validators and disable the button if the otp is invalid and Also show the error message.
 using formcontol like following:
 Html Code :
 ```
<ng-otp-input [config]="{length:6,containerClass:'otp-container-box',inputClass:'otp-input-box'}"
      [formCtrl]="OTP"></ng-otp-input>
```
Typescript Code:
```
 this.OTP = new FormControl('', [
      Validators.required,
      Validators.pattern('^[0-9]{6}$')
    ]);
```

**Comment by code-farmz** [comment]
you can add following condition to your button `[disabled]='OTP?.invalid && (OTP?.dirty || OTP?.touched)'` .Also supply null value instead of empty string to your otp control

**Comment by kcss-ashvini** [comment]
@code-farmz Thank you !
