### ISSUE TITLE
angular "^16.2.0"

### ISSUE THREAD

**Issue by MohhamedHassan** [code-farmz/ng-otp-input#122]
angular "^16.2.0"  with   "ng-otp-input": "^1.9.3"
first issue i should use -f flag to install the package
second when i try to use any boolean option like this [allowNumbersOnly]='true' i get this error
Can't bind to 'allowNumbersOnly' since it isn't a known property of 'ng-otp-input'.
1. If 'allowNumbersOnly' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.ngtsc(-998002)

**Comment by code-farmz** [comment]
@MohhamedHassan  please share your module details where you imported the OTP module or better provide a stackbliz example to reproduce the issue
