### ISSUE TITLE
Angular version is wrong for 1.9.4

### ISSUE THREAD

**Issue by giamy198** [code-farmz/ng-otp-input#124]
Hi,

on the description of dependency is present the message:

For angular version(V12 till V15)
    npm install --save ng-otp-input@1.9.4

but the 1.9.4 have as dependency the angular common 16.0.0
<img width="595" alt="image" src="https://github.com/user-attachments/assets/7acdb4bd-4862-451d-b1c2-4744eb82030a">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/47b0e823-dd2d-46d4-ab70-bc9f06e77465">

Best Regards,
Gianmario

**Comment by ShaoZhuan** [comment]
hitting this in npm install for angular v18, i believe is related issue
![image](https://github.com/user-attachments/assets/36037a0b-34de-4b68-b415-25aac656d931)

**Comment by code-farmz** [comment]
@giamy198  there were issues with v1.9.4 so the package has been removed and documentation updated to use v1.9.3 if you are below angular 16
@ShaoZhuan should be fixed with v2.0.2
