### ISSUE TITLE
Usage of inputmode="numeric" instead of type="tel"

### ISSUE THREAD

**Issue by cchangenot** [code-farmz/ng-otp-input#127]
Hello, just a little suggestion:
I can see that you are using `type="tel"` as input type when using `allowNumbersOnly: true`
Maybe using `inputmode="numeric"` instead for this case could make more sense.
(https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode)

**Comment by code-farmz** [comment]
It was done intentionally to fix an issue where number keyboard was not appearing in some of the devices.
