### ISSUE TITLE
OTP input in ios devices and mobile devices

### ISSUE THREAD

**Issue by JomalJohny** [code-farmz/ng-otp-input#15]
### ng-otp-input issues in ios devices and android [devices]
While adding the same number in the otp-input columns, the first number is only visible and others are invisible, also while clicking the keyboard back button the input style is breaking. 

> index.html

`<ng-otp-input class="otp-verify" inputmode="numeric" (keypress)="numberOTPOnly($event)" (onInputChange)="onOtpChangeEvent($event)"   dir="ltr"></ng-otp-input>  `

> index.ts
`  
config = {
    allowNumbersOnly: true,
    length: 10,
    disableAutoFocus: true,
    inputStyles: {
      'width': '10%',
    }
  }`

![2019-10-29](https://user-images.githubusercontent.com/43292719/67755508-4bf92600-fa5e-11e9-9167-02215ec6f5b9.png)

**Comment by code-farmz** [comment]
the first number is only visible is not an issue because every input will accept max one char

second one back button issue is fixed
