### ISSUE TITLE
allowNumbersOnly not working for cordova android

### ISSUE THREAD

**Issue by ctrlshifti** [code-farmz/ng-otp-input#16]
Even after setting allowNumbersOnly true,
input boxes will accept alphabets

**Comment by dangerhire8** [comment]
Ran into the same problem, even if `isPasswordInput` prop set up to `false`, input field changes type to 'text' not on 'number' as expected.

**Comment by code-farmz** [comment]
@dangerhire8  your changes are merged and published in the latest  version i.e 1.6.2 please verify if this fix your issue

**Comment by code-farmz** [comment]
> @dangerhire8 your changes are merged and published in the latest version i.e 1.6.2 please verify if this fix your issue

@T1TAN1UM can you please verify this one with latest version

**Comment by code-farmz** [comment]
closing as didn't hear back assuming this is fixed
