### ISSUE TITLE
Allownumbers only not working on Mobile device

### ISSUE THREAD

**Issue by AyazBelim** [code-farmz/ng-otp-input#18]
Allownumbers  not working on mobile apart from i have set allowNumbersOnly=true.

**Comment by code-farmz** [comment]
please specify the device bcs i have tested it in couple of devices and seems working fine to me

**Comment by AyazBelim** [comment]
![whatsapp-video-2019-11-20-at-148](https://user-images.githubusercontent.com/34475248/69221568-9bce9700-0b9d-11ea-8fec-ab75aa27cf81.gif)


I have attached Gif. please look this and this below is my config setting. i have tried in Andriod phones


config = {
    allowNumbersOnly: true,
    length: 4,
    isPasswordInput: false,
    disableAutoFocus: false,
    inputStyles: {
      'width': '60px',
      'height': '60px'
    }
  };

**Comment by code-farmz** [comment]
@AyazBelim  please verify if it's working now

**Comment by AyazBelim** [comment]
Working perfectly.. 
Thanks
