### ISSUE TITLE
setValue not working

### ISSUE THREAD

**Issue by csaptarshi26** [code-farmz/ng-otp-input#19]
**In HTML file I did this :**
<ng-otp-input #otpInput (onInputChange)="onOtpChange($event)" [config]="{length:4,allowNumbersOnly:true}"></ng-otp-input>

**and on Component File I did This:**
@ViewChild('otpInput') otpInputField: any;

but when i try to clear the value of otp field by setValue method i am getting the following error
**this.otpInputField.setValue is not a function**

**Comment by code-farmz** [comment]
Hi setValue is available only with version 1.6 or later so please try to update to latest version or please create a stackblitz of your problem

**Comment by code-farmz** [comment]
Closing this as no response and it’s working in stackblitz example
