### ISSUE TITLE
Update version to compatible for angular 8

### ISSUE THREAD

**Issue by AyazBelim** [code-farmz/ng-otp-input#21]
can you please update the version of this npm package ?

**Comment by code-farmz** [comment]
It’s working fine with angular can you please elaborate the problem

**Comment by AyazBelim** [comment]
Yes working fine. but just trying to clear warning of version problem.

**Comment by Badisi** [comment]
I think what the OP was saying is that your library generates warnings when used with angular > 6.

> Warning : unmeet peer dependencies regarding @angular/core and @angular/common

You need to update your peerDependencies in [package.json](https://github.com/code-farmz/ng-otp-input/blob/master/projects/ng-otp-input/package.json#L11) (and specifying only @angular/core should be enough though)
