### ISSUE TITLE
Enhancement - Add input placeholder via config

### ISSUE THREAD

**Issue by pandiyaavps** [code-farmz/ng-otp-input#23]

**Comment by pandiyaavps** [comment]
@code-farmz @DenysDzhel If you add input placeholder as config really good feature.

**Comment by Naveen-ux** [comment]
@pandiyaavps good i have created PR for the above feature :)

**Comment by pandiyaavps** [comment]
@Naveen-ux nice

**Comment by code-farmz** [comment]
> @pandiyaavps good i have created PR for the above feature :)

@pandiyaavps @naveen-ux can you specify the real world use case of placeholder(with some image reference etc) here as there can be only one character per input

**Comment by pandiyaavps** [comment]
@code-farmz suppose input box allow only number if we set placeholder as '#' ,For end user easily know number only to enter the input box.

**Comment by code-farmz** [comment]
> @code-farmz suppose input box allow only number if we set placeholder as '#' ,For end user easily know number only to enter the input box.

@pandiyaavps ok thank i will look into it ASAP till then you can use `otp-input` class which is applied to all inputs to set the placeholder

**Comment by Naveen-ux** [comment]
@code-farmz for reference only 
![otp](https://user-images.githubusercontent.com/59005146/71064265-aed08900-2194-11ea-8589-3c2fa8424137.gif)
for number only input field show have '#' as placeholder.

**Comment by code-farmz** [comment]
done refer to #25
