### ISSUE TITLE
Issue on iOS when pasting OTP from Messages app

### ISSUE THREAD

**Issue by damianoferrari** [code-farmz/ng-otp-input#27]
I discovered an issue on iOS when pasting an OTP that has been automatically retrieved from the Messages app.

Steps to reproduce:
1. trigger/request OTP generation
2. on the screen where the OTP is to be entered, tap on any input field that isn't the first one and wait for the SMS
3. when the SMS is received, tap on the iOS notification "From Messages xxxx"
4. the OTP will be pasted starting from the input field that received focus at point 2. The last input field will contain all the remaining digits in the OTP.

For instance, assuming an OTP of "1234", focusing on the third input field would cause the first two fields to be empty, the third one to have a value of "1", and the last one to have a value of "234".

See attached video for an actual example.

[OTP bug.mp4.zip](https://github.com/code-farmz/ng-otp-input/files/4075675/OTP.bug.mp4.zip)

**Comment by code-farmz** [comment]
Its working fine by copy paste Not sure weather we can control **From Message** paste via java script .

**Comment by kobusLink** [comment]
This is still an issue

**Comment by Linknpay** [comment]
Any fix ?

**Comment by alphagamer7** [comment]
+1
