### ISSUE TITLE
setValue is not working even with version 1.7.0

### ISSUE THREAD

**Issue by sudeeshbhaskar** [code-farmz/ng-otp-input#30]
not able setValue to ng-otp-input, I am using angular version 7 to use viewchild i tried both static value true and false.

**Comment by code-farmz** [comment]
@sudeeshbhaskar  can you please add [Stackblitz](https://stackblitz.com/edit/angular) link with your problem reproduction

**Comment by code-farmz** [comment]
@sudeeshbhaskar  please check the working [Stackblitz](https://stackblitz.com/github/code-farmz/ng-otp-input) here

**Comment by elinfinitoindia** [comment]
Cannot read property 'setValue' of undefined
