### ISSUE TITLE
How to resize the input boxes

### ISSUE THREAD

**Issue by iamade** [code-farmz/ng-otp-input#31]
Great component you have here but am having issues resizing it that is am trying to make them smaller and compact. please help I have checked google but nothing helpful yet

**Comment by code-farmz** [comment]
You can use input styles as give in [this stackblitz](https://stackblitz.com/edit/github-hq8tbx) or add input class and use styles to resize. Also for your reference, it's better to post such type of quires to StackOverflow instead
