### ISSUE TITLE
textbox not auto focus on ios

### ISSUE THREAD

**Issue by mikelim-cv** [code-farmz/ng-otp-input#32]
hi, having issue where it does not auto focus to the next textbox after input on my ios builds, however it works on android.

i believe its related to the closed issues previosly. 
https://github.com/code-farmz/ng-otp-input/issues/26

![ezgif-1-539a02eb8978](https://user-images.githubusercontent.com/61955486/76178398-348f2e00-61f2-11ea-9e4a-0847effbbbc2.gif)

**Comment by mikelim-cv** [comment]
currently i have to manually tap on each box to input a number on ios. it works like a charm on android though :) thx code-farm

**Comment by nicks258** [comment]
Did you find the solution?

**Comment by tabreztech** [comment]
@mikelim-cv i am facing the same issue. Did you find any other solution?

**Comment by nicks258** [comment]
@code-farmz  any updates?

**Comment by seeni5477** [comment]
> hi, having issue where it does not auto focus to the next textbox after input on my ios builds, however it works on android.
> 
> i believe its related to the closed issues previosly. #26
> 
> ![ezgif-1-539a02eb8978](https://user-images.githubusercontent.com/61955486/76178398-348f2e00-61f2-11ea-9e4a-0847effbbbc2.gif) [ ![ezgif-1-539a02eb8978](https://user-images.githubusercontent.com/61955486/76178398-348f2e00-61f2-11ea-9e4a-0847effbbbc2.gif) ](https://user-images.githubusercontent.com/61955486/76178398-348f2e00-61f2-11ea-9e4a-0847effbbbc2.gif) [ ](https://user-images.githubusercontent.com/61955486/76178398-348f2e00-61f2-11ea-9e4a-0847effbbbc2.gif)

now the same issue not working in android as well. Kindly please make it as workable for android.

**Comment by seeni5477** [comment]
I need a solution to that problem.

**Comment by Ruchita-Bhangre** [comment]
@code-farmz I am facing issue with the auto focus in the iOS device it is working fine in android and desktop. Can you please provide the solution to this problem.

**Comment by code-farmz** [comment]
@seeni5477 @nicks258 @mikelim-cv @Ruchita-Bhangre  can someone check and confirm this with the latest version v2.0.0 if this is still happening

**Comment by code-farmz** [comment]
closing this as no response please reopen if needed
