### ISSUE TITLE
Build error with versions angular 9.1.0 and typescript 3.8.3

### ISSUE THREAD

**Issue by VjRagss** [code-farmz/ng-otp-input#34]
![image](https://user-images.githubusercontent.com/43060259/78154475-ef10fa00-7459-11ea-98a1-98496861aef7.png)

**Comment by code-farmz** [comment]
[This may help](https://stackoverflow.com/a/60930633/5621827)

**Comment by VjRagss** [comment]
Removed node modules 
then 
npm clean cache --force
npm i
ng serve (or) npm run build

That worked . 

npm install will make postinstall ngcc and that will make the compilation works. So that fresh build happens where the ngcc fails to build few projects on its own with npm package installation
