### ISSUE TITLE
setValue ignores the disableAutoFocus setting

### ISSUE THREAD

**Issue by ArendBron** [code-farmz/ng-otp-input#36]
the value for `disableAutoFocus` is only checked initially, during the `ngAfterViewInit`. When programatically setting the value using `setValue`, the last field will always get focus. As i have set `disableAutoFocus` to true, i would not expect this behaviour.

**Comment by code-farmz** [comment]
@ArendBron can you please provide use case of the issue

**Comment by ArendBron** [comment]
I'm using this component inside a form with multiple components. Each of the fields could be filled with data from a backend. This is now the only component that forces itself to be focussed, and because of that also potentially scrolling to the field.

The usecase might be a bit shady for a one-time **password** input, but it fits our needs.. expect for the auto focus thing.

**Comment by ArendBron** [comment]
Version 1.7.1 resolves this issue, thanks @code-farmz
