### ISSUE TITLE
How to use focusTo 

### ISSUE THREAD

**Issue by pjsotou** [code-farmz/ng-otp-input#39]
Hi, thx for this component!
I need to focusTo the first element if the code was incorrect
How do I achieve this? 

I instantiate the ngOtpInputRef like this

  `@ViewChild('optinput') ngOtpInputRef:NgOtpInputComponent;`

And then when I check the code I reset the input and I try to focus to the first element.

```
 this.ngOtpInputRef.setValue("");
 this.ngOtpInputRef.focusTo(0); 
```

But the focus stays in the last position 

THX

**Comment by pjsotou** [comment]
I will able to implement this! 
Hope help someone 
      let id = this.ngOtpInputRef.appendKey(`otp_${0}`);
      this.ngOtpInputRef.focusTo(id);

Maybe it's a good idea to encapsulate this method 
Thx!

**Comment by nicks258** [comment]
Hello @pjsotou can you explain your code and what is `otp_${0}`
