### ISSUE TITLE
Error: Uncaught (in promise): Error: Template parse errors: Can't bind to 'config' since it isn't a known property of 'ng-otp-input'

### ISSUE THREAD

**Issue by surendra-17** [code-farmz/ng-otp-input#43]
ionic project
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/core": "^1.4.0",
    "@capacitor/ios": "^1.4.0",
    "@ionic-native/core": "^5.19.1",
    "@ionic-native/file": "^5.19.1",
    "@ionic-native/http": "^5.19.1",
    "@ionic-native/printer": "^5.19.1",
    "@ionic/angular": "^4.11.8",
    "cordova-android": "8.1.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-advanced-http": "^2.3.1",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-printer": "^0.8.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^2.6.11",
    "ng-otp-input": "^1.7.1",
    "rxjs": "^6.5.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

**Comment by iOSCuriosity** [comment]
try to add
`import { NgOtpInputModule } from  'ng-otp-input';`
in the same child module you want to use it.

I wanted to use it in my home page so I've added it in my home page module file and its working fine. Hope you got it!

**Comment by surendra-17** [comment]
> try to add
> `import { NgOtpInputModule } from 'ng-otp-input';`
> in the same child module you want to use it.
> 
> I wanted to use it in my home page so I've added it in my home page module file and its working fine. Hope you got it!

can i import these on app.module.ts

**Comment by surendra-17** [comment]
thanks its working
