### ISSUE TITLE
Can we have readonly status for this input?

### ISSUE THREAD

**Issue by frystalizer** [code-farmz/ng-otp-input#45]
I am currently using this component. There is additional requirement that once the otp is verified, the otp input should be read only to prevent the user from editing it.

Currently there is no such properties to configure for this.

**Comment by code-farmz** [comment]
you can get the form instance of the component example

Declare your component with has value

`<ng-otp-input #ngOtpInput ></ng-otp-input>`

Get  component instance using `ViewChild `

`
  @ViewChild('ngOtpInput', { read: false}) ngOtpInput: any;`

Then access the otpForm instance and call disable method

` this.ngOtpInput.otpForm.disable()`

[Live Demo](https://stackblitz.com/edit/github-fonawa?file=src%2Fapp%2Fapp.component.ts)
