### ISSUE TITLE
Issue with ionic ios build

### ISSUE THREAD

**Issue by farazahmadvaival** [code-farmz/ng-otp-input#48]
I used this plugin for ionic application with angular 9. It was working fine for android. but on ios device it is adding white space between keyboard and ng-otp-input. please provide any fixation for this.

**Comment by iAmServer** [comment]
Did you fix this @farazahmadvaival

**Comment by binhnt13682104** [comment]
Maybe you can try:
```
ion-content{
    --keyboard-offset: 0 !important;
  }
```

<img width="849" alt="Screen Shot 2021-01-11 at 08 26 28" src="https://user-images.githubusercontent.com/66429458/104140983-f4d33d00-53e6-11eb-890f-f39257f45ac7.png">
