### ISSUE TITLE
feat: autocomplete="one-time-code"

### ISSUE THREAD

**Issue by dylanvdmerwe** [code-farmz/ng-otp-input#51]
Firstly, great work on this component!

I was wondering if it is possible to implement the `autocomplete="one-time-code"` somehow that will read codes from SMS?

![image](https://user-images.githubusercontent.com/2852839/92458044-3d72b380-f1c5-11ea-9e05-8cabc8febf95.png)

**Comment by ajarudingunga** [comment]
+1 for this feature.

**Comment by Jucapo** [comment]
+1    Any solution ?

**Comment by code-farmz** [comment]
@dylanvdmerwe I have tried to implement this in the latest version with some more changes so it can fill in the code when user select **from message** can you please check once if that works

**Comment by bllue78** [comment]
For some reason we are stuck at Angular 8 and can only use max version 1.8.1. Just want to confirm has autocomplete="one-time-code" feature been included in 1.8.1?

> @dylanvdmerwe I have tried to implement this in the latest version with some more changes so it can fill in the code when user select **from message** can you please check once if that works

**Comment by spock123** [comment]
Anyone got this working? It doesn't seem to pick up pincodes from SMS messages at all.

**Comment by code-farmz** [comment]
This seems working fine with latest version check screen recording below
https://github.com/user-attachments/assets/fe8bf192-1807-41a2-98cd-e3f4f82c222e
