### ISSUE TITLE
onInputChange did trigger twice when copy and paste. 

### ISSUE THREAD

**Issue by Xrex-FrankHsu** [code-farmz/ng-otp-input#53]
`config: {
  length: 5,
 disableAutoFocus: false
}`

If I copy "ABCDE" and paste to input, onInputChange did trigger twice.
How can I fix it?  thanks.

**Comment by code-farmz** [comment]
not able to reproduce it can you please add a small video for the issue

**Comment by suneelpondric** [comment]
@Xrex-FrankHsu Hey I am facing the same issue, did you find a solution for it! If yes please share!
