### ISSUE TITLE
After clicking on the input, the cursor shows, when you type an input, it doesn't update the value but moves to next input

### ISSUE THREAD

**Issue by AbRetroDev** [code-farmz/ng-otp-input#54]
When you have entered your otp, and you realize you typed a character wrong, you click on the character you want to fix, you will see a cursor, but when you type a char it doesn't update, it only moves to the next input box.

**Comment by code-farmz** [comment]
To replace the char it should be in the selected state otherwise it will move to the next input since only one char allowed per input
![image](https://user-images.githubusercontent.com/19927847/98506596-df745200-2281-11eb-91c2-1e73bfc99121.png)
