### ISSUE TITLE
Feature: refactor with ControlValueAccessor

### ISSUE THREAD

**Issue by vorant94** [code-farmz/ng-otp-input#55]
What do you think about refactoring the lib to use Angular [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) in order to work within template driven and reactive forms?

I can take this work on me and then open pull request, if you wish. The goal of this issue is to clarify whether this feature is needed at all. Because if not (maybe you already thought about it and decided not to do it for some particular reason), there is no point for me to start implementing it...

**Comment by code-farmz** [comment]
implemented with 1.7.7 release
