### ISSUE TITLE
Pressing 'enter' while in OTP not submitting form

### ISSUE THREAD

**Issue by cyfer1313** [code-farmz/ng-otp-input#65]
Angular 8.1.3
NG-opt-input: 1.7.1
Using Chrome (latest)

I have a form which has been working for a while. For accessibly and ease of use, we'd like to be able to press the 'enter' key when in the last entry of the box to submit the form. It doesn't work. When I tab out of OTP onto another field. It works.

OTP is enabling/disabling the submit button. So I know it's not a valid/dirty/etc issue. And the enter key works on other fields. 

Thoughts?

**Comment by cyfer1313** [comment]
To elaborate, I think the issue is actual that the keydown code on the individual fields is capturing the 'enter' key and not handling it. So the value never 'submits' the code. (working theory). Thoughts?

**Comment by anupwritescode** [comment]
This library will only handle inputs and not the submit button. You will have to create the form and submit it by yourself. A workaround is to submit when an enter key is pressed and the length of the otp string equals to the desired one.

**Comment by cyfer1313** [comment]
I think you're missing what I'm saying. Inputs such as this control should never submit. By default, forms with a submit button will submit when you are in a form field (textbox) and hit the enter button. So in my case, i enter 6 numbers into your code, but when I hit enter when I'm done...nothing happens. I'd expect the master form to submit. But when I looked into your code, the code where you capture keyboard entries looks like it was also capturing the enter key. When this happened, the enter key was never propogated up to the actual form since it was already 'handled'.

**Comment by code-farmz** [comment]
@cyfer1313  sorry for the delayed response I have tried to capture the enter event outside of this component and I was able to do so with no issues.Below is the stack blitz example for the same try pressing enter inside any box and you will get the alert

https://stackblitz.com/edit/github-kchaub?file=src/app/app.component.ts

**Comment by code-farmz** [comment]
closing this as no response

**Comment by pankajparkar** [comment]
@code-farmz thanks for the hint.

I used `(keyup.enter)="submit()"` on my form attribute. Cheers 🥳
