### ISSUE TITLE
ERROR in Metadata version mismatch for module ../node_modules/ng-otp-input/ng-otp-input.d.ts, found version 4, expected 3, resolving symbol AppModule 

### ISSUE THREAD

**Issue by ANKIT-MONDAL-NITJSR** [code-farmz/ng-otp-input#67]
I am using ng-otp-input in my angular4 projet. but metadata version is not matching with my project. How to resolve ?

**Comment by code-farmz** [comment]
please provide more details like error screenshot etc

**Comment by ANKIT-MONDAL-NITJSR** [comment]
@code-farmz 
Have already resolved the issue. The main problem was, I was using this library in my angular4 project. So, what I have done is :

Simply change the angular version from 4 to 5 and it is now working fine.
