### ISSUE TITLE
throwing error "Cannot read property 'setValue' of undefined"

### ISSUE THREAD

**Issue by kishan-cool** [code-farmz/ng-otp-input#68]
Hi, 

I have implemented this in my site I have 2 files for login one for mobile and one for desktop but when I am trying to use disable, set value, enable on mobile site it is throwing "Cannot read property 'setValue' of undefined", and this same code with the same configuration it is working in the desktop file are different for mobile and desktop but code is same for OTP varification

**Comment by code-farmz** [comment]
can you please provide you code example here

**Comment by code-farmz** [comment]
closing as there is no example provided here
