### ISSUE TITLE
On allowing only numbers, the input type changes to "tel" and it is allowing space and - 

### ISSUE THREAD

**Issue by basant807** [code-farmz/ng-otp-input#69]
On allowing only numbers, the input type changes to "tel" and it is allowing space and -

**Comment by webacers** [comment]
+1

**Comment by code-farmz** [comment]
@basant807  yes it changes to tel and was done intentionally to fix one of the bugs. But I don't see it allow to enter space can you provide [stackblitz](https://stackblitz.com/) link for the same.
