### ISSUE TITLE
Lag in key detection

### ISSUE THREAD

**Issue by rishikesh-janrao** [code-farmz/ng-otp-input#72]
Hello,
There is bit lag in reading last digit in this feature.
Also let say I press 1 and without releasing key I press 2 , So it should detect keypress events only and not key release.
i.e. 12 should be output but it receives only 1 and not 2.

Majority peoples speed-type their OTPs so in that case this feature of yours is failing.
However great work @code-farmz !!

**Comment by code-farmz** [comment]
@rishikesh-janrao  thanks for the updated added tracking on keydown in latest version and it should now fix the issue
