### ISSUE TITLE
Change to uppercase character

### ISSUE THREAD

**Issue by anuj9196** [code-farmz/ng-otp-input#76]
**Feature Request**

In my application, I want to visualize the input alphabetical OTP as an uppercase character.

As this feature is not inbuilt supported, I tried using the `setValue()` method on each change event.

```
onOtpChange($event) {
  this.otpRef.setValue($event.toUpperCase());
}
```

But this creates an infinite loop of the input-output cycle.

Giving an option to set it as configuration would be more helpful

```
config = {
  allUpperCase: true
}
```

**Comment by code-farmz** [comment]
implemented the letterCase functionality in 1.8.1 version
