### ISSUE TITLE
(onInputChange) event is not invoking my custom method

### ISSUE THREAD

**Issue by HarshaChinni** [code-farmz/ng-otp-input#78]
<img width="589" alt="Screen Shot 2021-11-04 at 10 54 06 AM" src="https://user-images.githubusercontent.com/29237975/140383774-55a671cb-0a34-4e16-b8ae-345a8b4d6533.png">

Even when the method doMFAChallenge() is present, it's say can not find the method declaration. 

The version used for the ng-otp-input package is "^1.8.1"

Can someone take a look and see what is happening here?

**Comment by code-farmz** [comment]
@HarshaChinni  please provide working [stackblitz](https://stackblitz.com/github/code-farmz/ng-otp-input) for the issue

**Comment by FJMentz** [comment]
By looking at the screenshot, it looks like you're closing the tag after `[config]="config">`, (onInputChange) should still be contained within the opening tag.

**Comment by code-farmz** [comment]
closing this as this seems to be a code issue as mentioned above.Feel free to reach back with working stackblitz example
