### ISSUE TITLE
CSP configuration that blocked inline event

### ISSUE THREAD

**Issue by frystalizer** [code-farmz/ng-otp-input#79]
When we set the configuration to digit only, the `number-only` directive will automatically append this inline script
`'onkeypress', 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 0')`
This when met with the CSP that doesn't allow `unsafe-inline` will throw error in console log as below.

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "default-src 'self' https: blob:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.`

By far from what I know that we should use the (keypress) binding to a function instead of appending the script directly.

**Comment by code-farmz** [comment]
@frystalizer  can you create a [stackblitz example](https://stackblitz.com/github/code-farmz/ng-otp-input) for this issue and share the link here

**Comment by frystalizer** [comment]
Hi @code-farmz, please find the link below:

https://github-mxxdog.stackblitz.io

![image](https://user-images.githubusercontent.com/15686016/141747196-1cf74006-1aeb-4293-bc95-efb80b74b630.png)

**Comment by code-farmz** [comment]
Thanks, @frystalizer  I will try to fix the issue in the coming release

**Comment by code-farmz** [comment]
the directive is removed in 1.8.3 the issue should be fixed now
