### ISSUE TITLE
AutoFocus

### ISSUE THREAD

**Issue by honeykpc** [code-farmz/ng-otp-input#8]
Hi,
I recently came across this plugin and found it really useful. 
However, it would be awesome to have an 'autofocus' feature on the 1st Input when we accessing the app from Safari (iOS). 
For now, I have to manually target the DOM elements to find the 1st input field to show it focused. 

Is there any better way to do that?

**Comment by code-farmz** [comment]
@honeykpc will look into this issue and update here by eow

**Comment by honeykpc** [comment]
@code-farmz , great! Thank you so much. I'll keep an eye out.

**Comment by code-farmz** [comment]
@honeykpc  this is done please update to latest version

**Comment by honeykpc** [comment]
> 
> 
> @honeykpc this is done please update to latest version

Great! Thank you so much again.

**Comment by nicks258** [comment]
Its not working for ios 5.1.1.

**Comment by deverma245** [comment]
Is it possible to focus the next empty input box when end user try to click on any other empty input box.
