### ISSUE TITLE
SetValue breaks if not containerItem is null

### ISSUE THREAD

**Issue by FJMentz** [code-farmz/ng-otp-input#82]
Please see [line 172 in ng-otp-input.component.ts](https://github.com/code-farmz/ng-otp-input/blob/639927ee7e3addc38443463644d4b618fec9f146/projects/ng-otp-input/src/lib/components/ng-otp-input/ng-otp-input.component.ts#L172)

We're not checking for null before using it

**Comment by code-farmz** [comment]
Hi, @FJMentz Container item will always be there you can check the HTML view for the same.So no need to put a null check in the component

![image](https://user-images.githubusercontent.com/19927847/151485084-383a4038-8f87-43eb-a907-f29dd2967a3f.png)

**Comment by FJMentz** [comment]
Hey @code-farmz , thanks for the quick feedback! It might be something weird with the angular platform, because if I have disableAutoFocus set to false, I get this behaviour:
![image](https://user-images.githubusercontent.com/17801831/151492076-0a27ec47-8fcb-4fa5-ba9f-8f9ee78f4d7e.png)
