### ISSUE TITLE
Form does not get submitted when using numeric input

### ISSUE THREAD

**Issue by ArendBron** [code-farmz/ng-otp-input#85]
If you configure the OTP input to only allow numbers, pressing enter will no longer submit the surrounding form.

Created a [small StackBlitz example](https://stackblitz.com/edit/github-euarbk?devtoolsheight=33&file=src/app/app.component.html) which has 2 OTP inputs, one alphanumeric and one numeric. Pressing enter in the first submits the form (shown in the console), pressing enter in the second does not.

**Comment by code-farmz** [comment]
fixed in [1.8.3](https://stackblitz.com/edit/github-euarbk-5so8ac?devtoolsheight=33&file=package.json)
