### ISSUE TITLE
clearing values focus on last box

### ISSUE THREAD

**Issue by dhivyapriya1998** [code-farmz/ng-otp-input#88]
Im trying to clear values of input after some time interval.

by using  this.ngOtpEmailInput.setValue(0);
inputs getting cleared but the focus is on the last input instead of first.

 config = {
    allowNumbersOnly: true,
    length: 4,
    isPasswordInput: false,
    disableAutoFocus: true,
    placeholder: '',
    inputStyles: {
      'width': '50px',
      'height': '30px',
      fontSize: '16px'
    }
  };

**Comment by code-farmz** [comment]
get the latest version 1.9.1 and use the following code to focus on the first element

 let eleId=this.ngOtpInputRef.getBoxId(0);
    this.ngOtpInputRef.focusTo(eleId);

you can read more under **Focus to Specific box** section of readme file
