### ISSUE TITLE
 Clicking backspace moves the cursor back to the prior box, but does not delete the number in that box.

### ISSUE THREAD

**Issue by keval101** [code-farmz/ng-otp-input#89]
**Actual Result:**

Tapping backspace moves the cursor to the prior box and selects the number in it, but does not clear it. Clicking backspace again deletes this number and moves to the prior box, selecting that number. Typing a new number will replace the number in the current box, but this is not at all intuitive and creates a very confusing user experience. 

**Expected Result:**
Tapping the backspace key should delete the prior value, not just move the cursor back and select it. If all 4th boxes are filled, clicking backspace once should only clear 4th box but not move the cursor back to 3rd box, a second click should clear 3rd box and leave the cursor in that box, and so on.

https://user-images.githubusercontent.com/62419921/160071359-097f7d77-89fe-4412-96c7-864658338688.mp4

**Comment by btxtiger** [comment]
Found it also very confusing

**Comment by code-farmz** [comment]
done in the latest version 1.9.1
