### ISSUE TITLE
Null Injection Error Angular 13

### ISSUE THREAD

**Issue by nickLiechti** [code-farmz/ng-otp-input#90]
I Get the Error :  
  ERROR NullInjectorError: R3InjectorError(AppModule)[KeysPipe -> KeysPipe -> KeysPipe]: 
  NullInjectorError: No provider for KeysPipe!

When importing ng-otp-input

In Angular 13

**Comment by code-farmz** [comment]
@nickLiechti  can you please provide stackblitz example for the problem

**Comment by code-farmz** [comment]
closing this as didn't hear back and not able to reproduce
