### ISSUE TITLE
Not working in my project

### ISSUE THREAD

**Issue by heyashwani** [code-farmz/ng-otp-input#93]
My project is in angular 12. when i try to install the package using "npm install --save ng-otp-input" then error occured.

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular/http@7.2.15
npm ERR! Found: @angular/core@7.1.4
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"7.1.4" from @angular/animations@7.1.4
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"~7.1.0" from the root project
npm ERR!   peer @angular/core@"7.1.4" from @angular/common@7.1.4
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"7.1.4" from @angular/forms@7.1.4
npm ERR!     node_modules/@angular/forms
npm ERR!       peer @angular/forms@">=6.0.0 <8.0.0" from @ng-select/ng-select@2.20.5
npm ERR!       node_modules/@ng-select/ng-select
npm ERR!         @ng-select/ng-select@"^2.20.5" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @angular/common@"7.1.4" from @angular/platform-browser@7.1.4
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"7.1.4" from @angular/forms@7.1.4
npm ERR!       node_modules/@angular/forms
npm ERR!         peer @angular/forms@">=6.0.0 <8.0.0" from @ng-select/ng-select@2.20.5
npm ERR!         node_modules/@ng-select/ng-select
npm ERR!         1 more (the root project)
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     10 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!   15 more (@angular/forms, @angular/platform-browser, ...)

**Comment by code-farmz** [comment]
try using --force command or try to put a question on StackOverflow instead
