### ISSUE TITLE
While installing ng-otp-input getting this error! 

### ISSUE THREAD

**Issue by premkumar4855** [code-farmz/ng-otp-input#94]
unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: neftx-hms@11.0.0
npm ERR! Found: zone.js@0.11.7
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.11.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"11.0.3" from the root project
npm ERR!   peer @angular/core@">=6.0.0" from ng-otp-input@1.7.1
npm ERR!   node_modules/ng-otp-input
npm ERR!     ng-otp-input@"1.7.1" from the root project
npm ERR!   1 more (@angular/common)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/prem/.npm/eresolve-report.txt for a full report.

**Comment by code-farmz** [comment]
which angular version you are using

**Comment by premkumar4855** [comment]
we are using "@angular/core": "11.0.3"

**Comment by SanjidHaque** [comment]
use --force command @premkumar4855

**Comment by code-farmz** [comment]
closing as might be resolved with --force command
