### ISSUE TITLE
allowNumbersOnly:true read from system messages disappear 

### ISSUE THREAD

**Issue by khaled-elrifaay** [code-farmz/ng-otp-input#99]
if i put allowNumbersOnly:true in options 
read from system messages disappear 

<img width="414" alt="Screen Shot 2022-11-13 at 4 23 34 PM" src="https://user-images.githubusercontent.com/22242270/201526772-b11210a8-1e08-46c9-a0f4-2766370c5cdf.png">

**Comment by code-farmz** [comment]
from the message is not the feature of the component. AllowNumberOnly will change input type to tel which may be not supported for `From Messages`
